# https://taskfile.dev

version: '3'

vars:
  KAFKA_TOPIC: 'orders'

tasks:
  go:run_order_service:
    desc: "runs order service"
    cmds:
      - CONFIG_PATH="./config/local.yml" ENV="local" go run cmd/order-service/main.go
    silent: true

  go:run_migrator:
    desc: "runs migrations for database"
    cmds:
      - go run cmd/migrator/main.go
    silent: true

  go:run_order_generator:
    desc: "runs order generator"
    cmds:
      - go run cmd/order-generator/main.go
    silent: true

  go:tidy:
    desc: "synchronizes go dependencies"
    cmds:
      - go mod tidy
    silent: true

  go:fmt:
    desc: "formats all .go files"
    cmds:
      - go fmt ./...
    silent: true

  docker:up:
    desc: "builds and runs docker containters"
    cmds:
      - docker compose up -d
    silent: true
  
  docker:down:
    desc: "stops and deletes docker containers"
    cmds:
      - docker compose down -v
    silent: true
  
  docker:restart:
    desc: "restarts docker containers"
    cmds:
      - docker compose restart
    silent: true

  docker:list:
    desc: "lists all running docker images"
    cmds:
      - docker ps
    silent: true

  docker:build:
    desc: "builds all docker images"
    cmds:
      - docker compose build
    silent: true

  default:
    desc: "lists all task cmds"
    cmds:
      - task --list-all
    silent: true