env: ${ENV}

postgres:
  username: testuser
  password: 1234
  host: localhost
  port: 5432
  database: orderservice_db

redis:
  host: localhost
  port: 6379
  db: 0
  password: '1234'

kafka:
  bootstrap.servers:
    - 'localhost:9092'
  topic: 'orders'

  producer:
    acks: -1
    enable.idempotence: true
    retries: 5
    transactional.id: order-service-producer

  consumer:
    group.id: order-service-group
    auto.offset.reset: earliest
    enable.auto.commit: false
    security.protocol: PLAINTEXT
    isolation.level: 1
  
http_server:
  address: '0.0.0.0:8080'
  timeout: 4s
  idle_timeout: 30s
